# Hunter Thornsberry www.adventuresintechland.com
cachecreator = "" # username
creatorid = "" # geocache.com creatorid
datecreated = "" # date cache was created
dateaccess = "" # date cache data was access
lat = "" # latitude
lon = "" # longitude
cachegccode = "" # GCXXXXX code
cachename = "" # Name of the cache
cacheid = "" # Geocaching.com cacheid
cachetype = "" # Traditional, Mystery, Multi-Cache, EarthCache, Letterbox, etc
cachedifficulty = "" # 0.5 increments up to 5 (1.5/5)
cacheterrain = "" # 0.5 increments up to 5 (2.0/5)
cachecontainer = "" # Micro, Small, Regular, Large
country = "" # Country the cache is in
state = "" # State or Province the cache is in
longdesc = "" # long description
hints = "" # hints
cacheurl = "" # link to cache

def createGPX(cachecreator, creatorid, datecreated, dateaccess, lat, lon, cachegccode, cachename, cacheid, cachetype, cachedifficulty, cachecontainer, cacheterrain, country, state, longdesc, hints, cacheurl):
    f = open('output/' + cachegccode + '.GPX', 'w')
    f.write('<?xml version="1.0" encoding="utf-8"?> \n')
    f.write('<gpx xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" creator="Groundspeak, Inc. All Rights Reserved. http://www.groundspeak.com" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd http://www.groundspeak.com/cache/1/0 http://www.groundspeak.com/cache/1/0/cache.xsd" xmlns="http://www.topografix.com/GPX/1/0"> \n')
    f.write('  <name>Cache Listing Created By GeocacheToGPX</name> \n')
    f.write('  <desc>GPX file generated by  GeocacheToGPX</desc> \n')
    f.write('  <author>Account "' + cachecreator + '" From Geocaching.com</author> \n')
    f.write('  <email>hunter@hunterthornsberry.com</email> \n')
    f.write('  <url>http://www.adventuresintechland.com</url> \n')
    f.write('  <urlname>AdventuresInTechland</urlname> \n')
    f.write('  <time>' + datecreated + '</time> \n')
    f.write('  <keywords>cache, geocache</keywords> \n')
    f.write('  <bounds minlat="' + lat + '" minlon="'+ lon + '" maxlat="' + lat + '" maxlon="' + lon + '" /> \n')
    f.write('  <wpt lat="' + lat + '" lon="' + lon + '"> \n')
    f.write('    <time>' + dateaccess + '</time> \n')
    f.write('    <name>' + cachegccode + '</name> \n')
    f.write('    <desc>' + cachename + ' by ' + cachecreator + ', ' + cachetype + ' (' + cachedifficulty + '/' + cacheterrain + ')</desc> \n')
    f.write('    <url>' + cacheurl + '</url> \n')
    f.write('    <urlname>' + cachename + '</urlname> \n')
    f.write('    <sym>Geocache</sym> \n')
    f.write('    <type>Geocache|' + cachetype + '</type> \n')
    f.write('    <geocachetogpx:cache id="' + cacheid + '" available="True" archived="False" xmlns:groundspeak="http://www.groundspeak.com/cache/1/0"> \n')
    f.write('      <geocachetogpx:name>' + cachename + '</groundspeak:name> \n')
    f.write('      <geocachetogpx:placed_by>' + cachecreator + '</groundspeak:placed_by> \n')
    f.write('      <geocachetogpx:owner id="' + creatorid + '">' + cachecreator + '</groundspeak:owner> \n')
    f.write('      <geocachetogpx:type>' + cachetype + '</groundspeak:type> \n')
    f.write('      <geocachetogpx:container>' + cachecontainer + '</groundspeak:container> \n')
    f.write('      <geocachetogpx:difficulty>' + cachedifficulty + '</groundspeak:difficulty> \n')
    f.write('      <geocachetogpx:terrain>' + cacheterrain + '</groundspeak:terrain> \n')
    f.write('      <geocachetogpx:country>' + country + '</groundspeak:country> \n')
    f.write('      <geocachetogpx:state>' + state + '</groundspeak:state> \n')
    f.write('      <geocachetogpx:short_description html="True"> \n')
    f.write('      </geocachetogpx:short_description> \n')
    f.write('      <geocachetogpx:long_description html="True">' + longdesc + '</groundspeak:long_description> \n')
    f.write('      <geocachetogpx:encoded_hints>' + hints + '</groundspeak:encoded_hints> \n')
    f.write('    </geocachetogpx:cache> \n')
    f.write('  </wpt> \n')
    f.write('</gpx>')
    f.close()

createGPX(cachecreator, creatorid, datecreated, dateaccess, lat, lon, cachegccode, cachename, cacheid, cachetype, cachedifficulty, cachecontainer, cacheterrain, country, state, longdesc, hints, cacheurl)
